In [1]:
import pandas as pd

In [ ]:
df=pd.read_csv('KaggleV2-May-2016.csv')
# CSV dosyasını oku, 'df' kutusuna koy

In [ ]:
df.head()
# ilk 5 satırı getir

,PatientId,AppointmentID,Gender,ScheduledDay,AppointmentDay,Age,Neighbourhood,Scholarship,Hipertension,Diabetes,Alcoholism,Handcap,SMS_received,No-show
0,2.987250e+13,5642903,F,2016-04-29T18:38:08Z,2016-04-29T00:00:00Z,62,JARDIM DA PENHA,0,1,0,0,0,0,No
1,5.589978e+14,5642503,M,2016-04-29T16:08:27Z,2016-04-29T00:00:00Z,56,JARDIM DA PENHA,0,0,0,0,0,0,No
2,4.262962e+12,5642549,F,2016-04-29T16:19:04Z,2016-04-29T00:00:00Z,62,MATA DA PRAIA,0,0,0,0,0,0,No
3,8.679512e+11,5642828,F,2016-04-29T17:29:31Z,2016-04-29T00:00:00Z,8,PONTAL DE CAMBURI,0,0,0,0,0,0,No
4,8.841186e+12,5642494,F,2016-04-29T16:07:23Z,2016-04-29T00:00:00Z,56,JARDIM DA PENHA,0,1,1,0,0,0,No

In [ ]:
df.isnull().sum()
# boş hücreleri toplayıp sütunla
# 0 dan farklı sayı gelirse:"O sütunda o kadar tane boş hücre var" demek

PatientId         0
AppointmentID     0
Gender            0
ScheduledDay      0
AppointmentDay    0
Age               0
Neighbourhood     0
Scholarship       0
Hipertension      0
Diabetes          0
Alcoholism        0
Handcap           0
SMS_received      0
No-show           0
dtype: int64

In [ ]:
df.info()
"""Kaç satır veri var? 110527
Hangi sütun hangi veri tipinde? (sayı mı, yazı mı, tarih mi?)  14
Kaç tane dolu değer var?
Ne kadar bellek kullanıyor?
object:metin/yazı (örn: "F", "M", "No", "Yes")

"""

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 110527 entries, 0 to 110526
Data columns (total 14 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   PatientId       110527 non-null  float64
 1   AppointmentID   110527 non-null  int64
 2   Gender          110527 non-null  object
 3   ScheduledDay    110527 non-null  object
 4   AppointmentDay  110527 non-null  object
 5   Age             110527 non-null  int64
 6   Neighbourhood   110527 non-null  object
 7   Scholarship     110527 non-null  int64
 8   Hipertension    110527 non-null  int64
 9   Diabetes        110527 non-null  int64
 10  Alcoholism      110527 non-null  int64
 11  Handcap         110527 non-null  int64
 12  SMS_received    110527 non-null  int64
 13  No-show         110527 non-null  object
dtypes: float64(1), int64(8), object(5)
memory usage: 11.8+ MB

In [8]:
# şimdi tarihleri metinden zamana çevirelim
df['ScheduledDay'] = pd.to_datetime(df['ScheduledDay'])
# Pandas'a diyoruz ki: "Bu sütundaki yazıları tarih formatına çevir!"
# Çevrilmiş halini tekrar aynı sütuna kaydediyoruz. (Eskisinin üzerine yazıyoruz)

df['AppointmentDay'] = pd.to_datetime(df['AppointmentDay'])

In [ ]:
df.info()
# değişikliklerimize bakalım
# datetime64[ns] = "Artık bunlar gerçek tarih ve saat verisi!" demek.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 110527 entries, 0 to 110526
Data columns (total 14 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   PatientId       110527 non-null  float64
 1   AppointmentID   110527 non-null  int64
 2   Gender          110527 non-null  object
 3   ScheduledDay    110527 non-null  datetime64[ns, UTC]
 4   AppointmentDay  110527 non-null  datetime64[ns, UTC]
 5   Age             110527 non-null  int64
 6   Neighbourhood   110527 non-null  object
 7   Scholarship     110527 non-null  int64
 8   Hipertension    110527 non-null  int64
 9   Diabetes        110527 non-null  int64
 10  Alcoholism      110527 non-null  int64
 11  Handcap         110527 non-null  int64
 12  SMS_received    110527 non-null  int64
 13  No-show         110527 non-null  object
dtypes: datetime64[ns, UTC](2), float64(1), int64(8), object(3)
memory usage: 11.8+ MB

In [ ]:
df['No-show'].value_counts()
# no show adlı sütunun içindeki değerleri say , yes ve no sayısını göster
# yaklaşık %80 i gelmemiş

No-show
No     88208
Yes    22319
Name: count, dtype: int64

In [ ]:
df['No-show'].value_counts(normalize=True) * 100
# normalize=True -> sayıları değil oranları getir

No-show
No     79.806744
Yes    20.193256
Name: proportion, dtype: float64

In [ ]:
# Yaş sütununun temel istatistiklerini görelim
df['Age'].describe()

'''count:kaç tane yaş değeri var
    mean:ortalama yaş kaç
    std:yaşlar ortalamanın etrafına ne kadar dağılmış
    min->-1 çıkmış hata var
    %25-50-75:çeyreklik değerleri (medyan dahil)
    max'''

count    110527.000000
mean         37.088874
std          23.110205
min          -1.000000
25%          18.000000
50%          37.000000
75%          55.000000
max         115.000000
Name: Age, dtype: float64

In [19]:
# kaç yerde yaş neg görelim
df[df['Age']<0]
# yaşı 0 dan küçük olanları bul ve df[] ile getir

,PatientId,AppointmentID,Gender,ScheduledDay,AppointmentDay,Age,Neighbourhood,Scholarship,Hipertension,Diabetes,Alcoholism,Handcap,SMS_received,No-show
99832,4.659432e+14,5775010,F,2016-06-06 08:58:13+00:00,2016-06-06 00:00:00+00:00,-1,ROMÃO,0,0,0,0,0,0,No

In [21]:
# Yaşı 0'dan büyük veya eşit olanları tut, diğerlerini at. 
# böylece yaşı -1 olan satırı silmiş oluyoruz
# df['Age'] >= 0:"Yaş sütununda değeri 0 veya daha büyük olan satırları işaretle"
# df[ ... ]:Sadece işaretlenen (True olan) satırları getir
# df = ...:Bu filtrelenmiş halini tekrar df değişkenine kaydet (eskisinin üzerine yaz)
df = df[df['Age'] >= 0]

In [ ]:
print("Kalan satır sayısı:", len(df))
print("En küçük yaş:", df['Age'].min()) #en küçük yaş sorununu çözdük 
print("En büyük yaş:", df['Age'].max())

Kalan satır sayısı: 110526
En küçük yaş: 0
En büyük yaş: 115

In [23]:
df.columns

Index(['PatientId', 'AppointmentID', 'Gender', 'ScheduledDay',
       'AppointmentDay', 'Age', 'Neighbourhood', 'Scholarship', 'Hipertension',
       'Diabetes', 'Alcoholism', 'Handcap', 'SMS_received', 'No-show'],
      dtype='object')

In [24]:
# Sütun adını düzelt.Kelime hatası var onu düzeltelim
df.rename(columns={'Handcap': 'Handicap'}, inplace=True)
# df.rename(...):Sütun isimlerini değiştir
# columns={'Handcap': 'Handicap'}:"Handcap" olanı "Handicap" yap
# inplace=True:Değişikliği doğrudan df üzerine kaydet (yeni bir tablo oluşturma)

In [25]:
df.columns

Index(['PatientId', 'AppointmentID', 'Gender', 'ScheduledDay',
       'AppointmentDay', 'Age', 'Neighbourhood', 'Scholarship', 'Hipertension',
       'Diabetes', 'Alcoholism', 'Handicap', 'SMS_received', 'No-show'],
      dtype='object')